name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
        
    - name: Set up JDK 1.8
      uses: joschi/setup-jdk@v2
      with:
        java-version: '8'
    
    - name: list maven configuration
      run: cat $M2_HOME/conf/settings.xml
          
    
    - name: Build with Maven
      run: mvn clean install
